language: php
php:
  - "5.5"
  - "5.6"
  - "7.0"
  - "7.1"
  - "7.2"

before_script:
  - mkdir -p build/logs
  - composer install --dev --no-interaction
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "7.1" ]; then composer require php-coveralls/php-coveralls; fi;'

script:
  - vendor/bin/phpunit -c phpunit.xml --coverage-clover=build/logs/clover.xml --coverage-text
 
after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "7.1" ]; then php vendor/bin/php-coveralls -v; fi;'
